### ISSUE TITLE
Restore attributes other than health?

### ISSUE THREAD

**Issue by AlexNisnevich** [wordbots/wordbots-core#274]

**Comment by MichaelEbert** [comment]
Restoring health is more valuable than restoring other attributes, because it's so much easier to damage health. Additionally, you can always use health restoration, but can only use attribute restoration if the opponent has cards that damage your attributes. Therefore other attribute restoration would need to be much more powerful for the same cost to be competitive.
A "dispel" mechanic might be interesting - a way to reset a robot's attributes (except health) to its initial values. Could be used on allies or enemies, which gives it more utility than a simple restore.

**Comment by AlexNisnevich** [comment]
Good point, @MichaelEbert. Feel free to create an issue about some kind of "dispel" mechanic.
