### ISSUE TITLE
User agents must contain name of a popular browser

### ISSUE THREAD

**Issue by MichaelEbert** [wordbots/wordbots-core#419]
If the user agent does not contain the name of a popular browser, then the red header at the top of the page doubles in height and overlaps the menu.
This creates a problem when accessing the site through Palemoon, konqueror, or other relatively unused browsers.
This happens when the user agent does not contain any of the following strings:
firefox
chrome
msie
opera
safari
chromium
applewebkit
vivaldi

**Comment by AlexNisnevich** [comment]
Oh weird. Any idea why this happens?

**Comment by AlexNisnevich** [comment]
Oh, I see. The issue is that flexbox layout is not enabled for unusual user agents: https://www.reddit.com/r/webdev/comments/3mc44d/user_agents_and_flexbox_support_im_doing_a_little/

There's not really much we can do here, short of displaying some kind of error message. Flexbox is critical to the layout of Wordbots in many places.

**Comment by AlexNisnevich** [comment]
See #420.
